/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package engineer.enterprise.payroll.system;

import javax.swing.JOptionPane;

/**
 *
 * @author Mohamed
 */
public class Add_E extends javax.swing.JFrame {

    /**
     * Creates new form Add_E
     */
    public Add_E() {
        initComponents();
        this.setTitle("Add Engineer");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        idtext = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nametext = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        agetext = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        workhrstext = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setPreferredSize(new java.awt.Dimension(1090, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 40, 46, 29);

        idtext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(idtext);
        idtext.setBounds(340, 40, 300, 28);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(140, 130, 100, 29);

        nametext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(nametext);
        nametext.setBounds(340, 130, 290, 28);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Age");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(140, 240, 60, 29);

        agetext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(agetext);
        agetext.setBounds(340, 240, 290, 28);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Position");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(130, 350, 120, 29);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jTextField1);
        jTextField1.setBounds(340, 350, 300, 28);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Working hour");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(120, 450, 180, 29);

        workhrstext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(workhrstext);
        workhrstext.setBounds(340, 450, 300, 28);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineer/enterprise/payroll/system/icons8-plus-24.png"))); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 550, 240, 60);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineer/enterprise/payroll/system/icons8-go-back-24.png"))); // NOI18N
        jButton3.setText("Return back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(680, 550, 230, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineer/enterprise/payroll/system/icons8-age-48.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 230, 48, 60);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineer/enterprise/payroll/system/icons8-identity-theft-48.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 20, 48, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineer/enterprise/payroll/system/icons8-place-marker-48.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 330, 48, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineer/enterprise/payroll/system/icons8-autograph-48.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 120, 48, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineer/enterprise/payroll/system/icons8-clock-48.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 440, 50, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineer/enterprise/payroll/system/f153e729-628b-446c-a69c-217cde29c861.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1260, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

         if(nametext.getText().length()!=0&&idtext.getText().length()!=0&&jTextField1.getText().length()!=0&&agetext.getText().length()!=0&&workhrstext.getText().length()!=0){

        Boolean found=false;
        String name=nametext.getText();
        String id= idtext.getText();
        String position= jTextField1.getText();
        int age= Integer.parseInt(agetext.getText());
        int workingHour= Integer.parseInt(workhrstext.getText());
               for(int i=0;i<Engineer.eng.size();i++){
            if(id.equals(Engineer.eng.get(i).getID())){
                JOptionPane.showMessageDialog(this,"The ID is already found ", "Error",JOptionPane.ERROR_MESSAGE);
                found=true;
            }
        }
        if(found==false){
        Grade g=new Grade(workingHour,position);
        Employee e=new Engineer(id, name, age,g);
        e.Add();
        JOptionPane.showMessageDialog(this, "Done","Done",JOptionPane.INFORMATION_MESSAGE);
        nametext.setText("");
        idtext.setText("");
        jTextField1.setText("");
        agetext.setText("");
        workhrstext.setText("");
        }
       }
        else{
            JOptionPane.showMessageDialog(this,"Please enter all data required", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        Eng_form back= new Eng_form();
         back.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_E.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_E.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_E.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_E.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_E().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agetext;
    private javax.swing.JTextField idtext;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nametext;
    private javax.swing.JTextField workhrstext;
    // End of variables declaration//GEN-END:variables
}
