/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package engineer.enterprise.payroll.system;

import javax.swing.JOptionPane;

/**
 *
 * @author nesreen
 */
public class Add_T extends javax.swing.JFrame {

    /**
     * Creates new form Add_T
     */
    public Add_T() {
        initComponents();
         this.setTitle("Add Trainee");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IDText = new javax.swing.JTextField();
        NameText = new javax.swing.JTextField();
        AgeText = new javax.swing.JTextField();
        UniText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        GpaText = new javax.swing.JTextField();
        YearText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));
        setPreferredSize(new java.awt.Dimension(1090, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 100, 80, 36);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 30, 70, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Age");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 190, 100, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Universty name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 270, 190, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GPA");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 350, 80, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Acdemic Year");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 430, 180, 29);

        IDText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(IDText);
        IDText.setBounds(340, 30, 228, 28);

        NameText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(NameText);
        NameText.setBounds(340, 110, 228, 28);

        AgeText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(AgeText);
        AgeText.setBounds(340, 190, 228, 28);

        UniText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(UniText);
        UniText.setBounds(340, 270, 228, 28);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineer/enterprise/payroll/system/icons8-identity-theft-48.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 30, 50, 50);

        GpaText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(GpaText);
        GpaText.setBounds(340, 350, 228, 28);

        YearText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(YearText);
        YearText.setBounds(340, 440, 228, 28);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineer/enterprise/payroll/system/icons8-autograph-48.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 90, 95, 60);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineer/enterprise/payroll/system/icons8-age-48.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 180, 48, 50);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineer/enterprise/payroll/system/icons8-classroom-48.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 240, 80, 80);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineer/enterprise/payroll/system/icons8-numbers-48.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 340, 70, 50);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineer/enterprise/payroll/system/icons8-minus-1-year-48.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 410, 50, 70);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineer/enterprise/payroll/system/icons8-plus-24.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 550, 220, 60);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineer/enterprise/payroll/system/icons8-go-back-24.png"))); // NOI18N
        jButton2.setText("Return Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(590, 550, 240, 60);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/engineer/enterprise/payroll/system/f153e729-628b-446c-a69c-217cde29c861.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1100, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(NameText.getText().length()!=0&&IDText.getText().length()!=0&&AgeText.getText().length()!=0&&UniText.getText().length()!=0&&GpaText.getText().length()!=0){

        Boolean found=false;
        String name=NameText.getText();
        String id= IDText.getText();
        int Age= Integer.parseInt(AgeText.getText());
        String uni = UniText.getText();
        int GPA = Integer.parseInt(GpaText.getText());
      String year = YearText.getText();
        for(int i=0;i<trainee.tra.size();i++){
            if(id.equals(trainee.tra.get(i).getID())){
                found=true;
            }
        }
       if(found==false){
        Employee t=new trainee( id,  name,  Age, uni , GPA ,year );
        t.Add();
        JOptionPane.showMessageDialog(this, "Done","Done",JOptionPane.INFORMATION_MESSAGE);
        NameText.setText("");
        IDText.setText("");
        AgeText.setText("");
        UniText.setText("");
        GpaText.setText("");
       
        GpaText.setText("");
        YearText.setText("");
       }
       else{
           IDText.setText("");
           JOptionPane.showMessageDialog(this,"The ID is already found ", "Error",JOptionPane.ERROR_MESSAGE);
       }
       
      }
         else{
            JOptionPane.showMessageDialog(this,"Please enter all data required", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         Trainee_form Return = new Trainee_form();
         Return.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_T.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_T.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_T.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_T.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_T().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeText;
    private javax.swing.JTextField GpaText;
    private javax.swing.JTextField IDText;
    private javax.swing.JTextField NameText;
    private javax.swing.JTextField UniText;
    private javax.swing.JTextField YearText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
